### PR TITLE
Feb Details & 6 month template

### PR DESCRIPTION
**Pull request by ncphillips**

### CODE REVIEW

**Comment by evanepio** [comment]
Most of us just modify as needed. But if you're looking for approval: 👍

**Comment by ncphillips** [comment]
Hmm, looks like I don't have write access. It's not letting me merge.

**Comment by evanepio** [comment]
Your invitation is pending. Is there a way to accept it from your end?

**Comment by evanepio** [comment]
Try going here and accepting the invite:

https://github.com/peidevs

If not, I'll merge it.

**Pull request merged**
